# Generated by Django 3.0.6 on 2020-05-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trone', '0002_easyreg2'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyreg',
            name='vk',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='easyreg2',
            name='vk',
            field=models.CharField(default='', max_length=50),
        ),
    ]
