# Generated by Django 3.0.6 on 2020-06-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trone', '0006_auto_20200601_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadsReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(default='', max_length=50)),
                ('username2', models.CharField(default='', max_length=50)),
                ('username3', models.CharField(default='', max_length=50)),
                ('username4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='DuoEasy',
            new_name='DuoReg',
        ),
    ]
