# Generated by Django 3.0.6 on 2020-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trone', '0007_auto_20200602_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadsreg',
            name='username2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='squadsreg',
            name='username3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='squadsreg',
            name='username4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
