# Generated by Django 3.0.6 on 2020-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trone', '0010_praksreg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='praksreg',
            name='reserv1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='praksreg',
            name='reserv2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
